#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
#
# Source0 file verified with key 0x08C81B2C6CE95CA7 (cluster-devel@redhat.com)
#
Name     : libqb
Version  : 2.0.7
Release  : 9
URL      : https://github.com/ClusterLabs/libqb/releases/download/v2.0.7/libqb-2.0.7.tar.xz
Source0  : https://github.com/ClusterLabs/libqb/releases/download/v2.0.7/libqb-2.0.7.tar.xz
Source1  : https://github.com/ClusterLabs/libqb/releases/download/v2.0.7/libqb-2.0.7.tar.xz.asc
Summary  : libqb
Group    : Development/Tools
License  : LGPL-2.1
Requires: libqb-bin = %{version}-%{release}
Requires: libqb-lib = %{version}-%{release}
Requires: libqb-license = %{version}-%{release}
Requires: libqb-man = %{version}-%{release}
BuildRequires : buildreq-configure
BuildRequires : doxygen
BuildRequires : elfutils
BuildRequires : pkgconfig(check)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(libsystemd)
BuildRequires : pkgconfig(libxml-2.0)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# libqb
## What is libqb?
libqb is a library with the primary purpose of providing high-performance,
reusable features for client-server architecture, such as logging,
tracing, inter-process communication (IPC), and polling.

%package bin
Summary: bin components for the libqb package.
Group: Binaries
Requires: libqb-license = %{version}-%{release}

%description bin
bin components for the libqb package.


%package dev
Summary: dev components for the libqb package.
Group: Development
Requires: libqb-lib = %{version}-%{release}
Requires: libqb-bin = %{version}-%{release}
Provides: libqb-devel = %{version}-%{release}
Requires: libqb = %{version}-%{release}

%description dev
dev components for the libqb package.


%package doc
Summary: doc components for the libqb package.
Group: Documentation
Requires: libqb-man = %{version}-%{release}

%description doc
doc components for the libqb package.


%package lib
Summary: lib components for the libqb package.
Group: Libraries
Requires: libqb-license = %{version}-%{release}

%description lib
lib components for the libqb package.


%package license
Summary: license components for the libqb package.
Group: Default

%description license
license components for the libqb package.


%package man
Summary: man components for the libqb package.
Group: Default

%description man
man components for the libqb package.


%prep
%setup -q -n libqb-2.0.7
cd %{_builddir}/libqb-2.0.7
pushd ..
cp -a libqb-2.0.7 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1686149403
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
%configure --disable-static
make  %{?_smp_mflags}

unset PKG_CONFIG_PATH
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3"
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3"
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3"
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3"
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3"
%configure --disable-static
make  %{?_smp_mflags}
popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check
cd ../buildavx2;
make %{?_smp_mflags} check || :

%install
export SOURCE_DATE_EPOCH=1686149403
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libqb
cp %{_builddir}/libqb-%{version}/COPYING %{buildroot}/usr/share/package-licenses/libqb/9a647436aa2324c4cb849c6f3d31c392ed50d9bd || :
pushd ../buildavx2/
%make_install_v3
popd
%make_install
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/doxygen2man
/V3/usr/bin/qb-blackbox
/usr/bin/doxygen2man
/usr/bin/qb-blackbox

%files dev
%defattr(-,root,root,-)
/usr/include/qb/qbarray.h
/usr/include/qb/qbatomic.h
/usr/include/qb/qbconfig.h
/usr/include/qb/qbdefs.h
/usr/include/qb/qbhdb.h
/usr/include/qb/qbipc_common.h
/usr/include/qb/qbipcc.h
/usr/include/qb/qbipcs.h
/usr/include/qb/qblist.h
/usr/include/qb/qblog.h
/usr/include/qb/qbloop.h
/usr/include/qb/qbmap.h
/usr/include/qb/qbrb.h
/usr/include/qb/qbutil.h
/usr/lib64/libqb.so
/usr/lib64/pkgconfig/libqb.pc
/usr/share/man/man3/qb_array_create.3
/usr/share/man/man3/qb_array_create_2.3
/usr/share/man/man3/qb_array_elems_per_bin_get.3
/usr/share/man/man3/qb_array_free.3
/usr/share/man/man3/qb_array_grow.3
/usr/share/man/man3/qb_array_index.3
/usr/share/man/man3/qb_array_new_bin_cb_set.3
/usr/share/man/man3/qb_array_num_bins_get.3
/usr/share/man/man3/qb_atomic_init.3
/usr/share/man/man3/qb_atomic_int_add.3
/usr/share/man/man3/qb_atomic_int_compare_and_exchange.3
/usr/share/man/man3/qb_atomic_int_exchange_and_add.3
/usr/share/man/man3/qb_atomic_int_get.3
/usr/share/man/man3/qb_atomic_int_set.3
/usr/share/man/man3/qb_atomic_pointer_compare_and_exchange.3
/usr/share/man/man3/qb_atomic_pointer_get.3
/usr/share/man/man3/qb_atomic_pointer_set.3
/usr/share/man/man3/qb_hashtable_create.3
/usr/share/man/man3/qb_hdb_base_convert.3
/usr/share/man/man3/qb_hdb_create.3
/usr/share/man/man3/qb_hdb_destroy.3
/usr/share/man/man3/qb_hdb_handle_create.3
/usr/share/man/man3/qb_hdb_handle_destroy.3
/usr/share/man/man3/qb_hdb_handle_get.3
/usr/share/man/man3/qb_hdb_handle_get_always.3
/usr/share/man/man3/qb_hdb_handle_put.3
/usr/share/man/man3/qb_hdb_handle_refcount_get.3
/usr/share/man/man3/qb_hdb_iterator_next.3
/usr/share/man/man3/qb_hdb_iterator_reset.3
/usr/share/man/man3/qb_hdb_nocheck_convert.3
/usr/share/man/man3/qb_ipcc_connect.3
/usr/share/man/man3/qb_ipcc_context_get.3
/usr/share/man/man3/qb_ipcc_context_set.3
/usr/share/man/man3/qb_ipcc_disconnect.3
/usr/share/man/man3/qb_ipcc_event_recv.3
/usr/share/man/man3/qb_ipcc_fc_enable_max_set.3
/usr/share/man/man3/qb_ipcc_fd_get.3
/usr/share/man/man3/qb_ipcc_get_buffer_size.3
/usr/share/man/man3/qb_ipcc_is_connected.3
/usr/share/man/man3/qb_ipcc_recv.3
/usr/share/man/man3/qb_ipcc_send.3
/usr/share/man/man3/qb_ipcc_sendv.3
/usr/share/man/man3/qb_ipcc_sendv_recv.3
/usr/share/man/man3/qb_ipcc_verify_dgram_max_msg_size.3
/usr/share/man/man3/qb_ipcs_connection_auth_set.3
/usr/share/man/man3/qb_ipcs_connection_first_get.3
/usr/share/man/man3/qb_ipcs_connection_get_buffer_size.3
/usr/share/man/man3/qb_ipcs_connection_next_get.3
/usr/share/man/man3/qb_ipcs_connection_ref.3
/usr/share/man/man3/qb_ipcs_connection_service_context_get.3
/usr/share/man/man3/qb_ipcs_connection_stats_get.3
/usr/share/man/man3/qb_ipcs_connection_stats_get_2.3
/usr/share/man/man3/qb_ipcs_connection_unref.3
/usr/share/man/man3/qb_ipcs_context_get.3
/usr/share/man/man3/qb_ipcs_context_set.3
/usr/share/man/man3/qb_ipcs_create.3
/usr/share/man/man3/qb_ipcs_destroy.3
/usr/share/man/man3/qb_ipcs_disconnect.3
/usr/share/man/man3/qb_ipcs_enforce_buffer_size.3
/usr/share/man/man3/qb_ipcs_event_send.3
/usr/share/man/man3/qb_ipcs_event_sendv.3
/usr/share/man/man3/qb_ipcs_poll_handlers_set.3
/usr/share/man/man3/qb_ipcs_ref.3
/usr/share/man/man3/qb_ipcs_request_rate_limit.3
/usr/share/man/man3/qb_ipcs_response_send.3
/usr/share/man/man3/qb_ipcs_response_sendv.3
/usr/share/man/man3/qb_ipcs_run.3
/usr/share/man/man3/qb_ipcs_service_context_get.3
/usr/share/man/man3/qb_ipcs_service_context_set.3
/usr/share/man/man3/qb_ipcs_service_id_get.3
/usr/share/man/man3/qb_ipcs_stats_get.3
/usr/share/man/man3/qb_ipcs_unref.3
/usr/share/man/man3/qb_list_add.3
/usr/share/man/man3/qb_list_add_tail.3
/usr/share/man/man3/qb_list_del.3
/usr/share/man/man3/qb_list_empty.3
/usr/share/man/man3/qb_list_init.3
/usr/share/man/man3/qb_list_is_last.3
/usr/share/man/man3/qb_list_length.3
/usr/share/man/man3/qb_list_replace.3
/usr/share/man/man3/qb_list_splice.3
/usr/share/man/man3/qb_list_splice_tail.3
/usr/share/man/man3/qb_log_blackbox_print_from_file.3
/usr/share/man/man3/qb_log_blackbox_write_to_file.3
/usr/share/man/man3/qb_log_callsite_get.3
/usr/share/man/man3/qb_log_callsites_dump.3
/usr/share/man/man3/qb_log_callsites_register.3
/usr/share/man/man3/qb_log_ctl.3
/usr/share/man/man3/qb_log_ctl2.3
/usr/share/man/man3/qb_log_custom_close.3
/usr/share/man/man3/qb_log_custom_open.3
/usr/share/man/man3/qb_log_facility2int.3
/usr/share/man/man3/qb_log_facility2str.3
/usr/share/man/man3/qb_log_file_close.3
/usr/share/man/man3/qb_log_file_open.3
/usr/share/man/man3/qb_log_file_reopen.3
/usr/share/man/man3/qb_log_filter_ctl.3
/usr/share/man/man3/qb_log_filter_ctl2.3
/usr/share/man/man3/qb_log_filter_fn_set.3
/usr/share/man/man3/qb_log_fini.3
/usr/share/man/man3/qb_log_format_set.3
/usr/share/man/man3/qb_log_from_external_source.3
/usr/share/man/man3/qb_log_from_external_source_va.3
/usr/share/man/man3/qb_log_init.3
/usr/share/man/man3/qb_log_real_.3
/usr/share/man/man3/qb_log_real_va_.3
/usr/share/man/man3/qb_log_tags_stringify_fn_set.3
/usr/share/man/man3/qb_log_target_format.3
/usr/share/man/man3/qb_log_target_user_data_get.3
/usr/share/man/man3/qb_log_target_user_data_set.3
/usr/share/man/man3/qb_log_thread_priority_set.3
/usr/share/man/man3/qb_log_thread_start.3
/usr/share/man/man3/qb_loop_create.3
/usr/share/man/man3/qb_loop_destroy.3
/usr/share/man/man3/qb_loop_job_add.3
/usr/share/man/man3/qb_loop_job_del.3
/usr/share/man/man3/qb_loop_poll_add.3
/usr/share/man/man3/qb_loop_poll_del.3
/usr/share/man/man3/qb_loop_poll_low_fds_event_set.3
/usr/share/man/man3/qb_loop_poll_mod.3
/usr/share/man/man3/qb_loop_run.3
/usr/share/man/man3/qb_loop_signal_add.3
/usr/share/man/man3/qb_loop_signal_del.3
/usr/share/man/man3/qb_loop_signal_mod.3
/usr/share/man/man3/qb_loop_stop.3
/usr/share/man/man3/qb_loop_timer_add.3
/usr/share/man/man3/qb_loop_timer_del.3
/usr/share/man/man3/qb_loop_timer_expire_time_get.3
/usr/share/man/man3/qb_loop_timer_expire_time_remaining.3
/usr/share/man/man3/qb_loop_timer_is_running.3
/usr/share/man/man3/qb_map_count_get.3
/usr/share/man/man3/qb_map_destroy.3
/usr/share/man/man3/qb_map_foreach.3
/usr/share/man/man3/qb_map_get.3
/usr/share/man/man3/qb_map_iter_create.3
/usr/share/man/man3/qb_map_iter_free.3
/usr/share/man/man3/qb_map_iter_next.3
/usr/share/man/man3/qb_map_notify_add.3
/usr/share/man/man3/qb_map_notify_del.3
/usr/share/man/man3/qb_map_notify_del_2.3
/usr/share/man/man3/qb_map_pref_iter_create.3
/usr/share/man/man3/qb_map_put.3
/usr/share/man/man3/qb_map_rm.3
/usr/share/man/man3/qb_rb_chmod.3
/usr/share/man/man3/qb_rb_chown.3
/usr/share/man/man3/qb_rb_chunk_alloc.3
/usr/share/man/man3/qb_rb_chunk_commit.3
/usr/share/man/man3/qb_rb_chunk_peek.3
/usr/share/man/man3/qb_rb_chunk_read.3
/usr/share/man/man3/qb_rb_chunk_reclaim.3
/usr/share/man/man3/qb_rb_chunk_write.3
/usr/share/man/man3/qb_rb_chunks_used.3
/usr/share/man/man3/qb_rb_close.3
/usr/share/man/man3/qb_rb_create_from_file.3
/usr/share/man/man3/qb_rb_name_get.3
/usr/share/man/man3/qb_rb_open.3
/usr/share/man/man3/qb_rb_refcount_get.3
/usr/share/man/man3/qb_rb_shared_user_data_get.3
/usr/share/man/man3/qb_rb_space_free.3
/usr/share/man/man3/qb_rb_space_used.3
/usr/share/man/man3/qb_rb_write_to_file.3
/usr/share/man/man3/qb_skiplist_create.3
/usr/share/man/man3/qb_strerror_r.3
/usr/share/man/man3/qb_thread_lock.3
/usr/share/man/man3/qb_thread_lock_create.3
/usr/share/man/man3/qb_thread_lock_destroy.3
/usr/share/man/man3/qb_thread_trylock.3
/usr/share/man/man3/qb_thread_unlock.3
/usr/share/man/man3/qb_timespec_add_ms.3
/usr/share/man/man3/qb_trie_create.3
/usr/share/man/man3/qb_trie_dump.3
/usr/share/man/man3/qb_util_nano_current_get.3
/usr/share/man/man3/qb_util_nano_from_epoch_get.3
/usr/share/man/man3/qb_util_nano_monotonic_hz.3
/usr/share/man/man3/qb_util_set_log_function.3
/usr/share/man/man3/qb_util_stopwatch_create.3
/usr/share/man/man3/qb_util_stopwatch_free.3
/usr/share/man/man3/qb_util_stopwatch_sec_elapsed_get.3
/usr/share/man/man3/qb_util_stopwatch_split.3
/usr/share/man/man3/qb_util_stopwatch_split_ctl.3
/usr/share/man/man3/qb_util_stopwatch_split_last.3
/usr/share/man/man3/qb_util_stopwatch_start.3
/usr/share/man/man3/qb_util_stopwatch_stop.3
/usr/share/man/man3/qb_util_stopwatch_time_split_get.3
/usr/share/man/man3/qb_util_stopwatch_us_elapsed_get.3
/usr/share/man/man3/qb_util_timespec_from_epoch_get.3
/usr/share/man/man3/qbarray.h.3
/usr/share/man/man3/qbatomic.h.3
/usr/share/man/man3/qbdefs.h.3
/usr/share/man/man3/qbhdb.h.3
/usr/share/man/man3/qbipc_common.h.3
/usr/share/man/man3/qbipcc.h.3
/usr/share/man/man3/qbipcs.h.3
/usr/share/man/man3/qblist.h.3
/usr/share/man/man3/qblog.h.3
/usr/share/man/man3/qbloop.h.3
/usr/share/man/man3/qbmap.h.3
/usr/share/man/man3/qbrb.h.3
/usr/share/man/man3/qbutil.h.3

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/libqb/*

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libqb.so.100.3.1
/usr/lib64/libqb.so.100
/usr/lib64/libqb.so.100.3.1

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libqb/9a647436aa2324c4cb849c6f3d31c392ed50d9bd

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/doxygen2man.1
/usr/share/man/man8/qb-blackbox.8
